### ISSUE TITLE
su from adb shell has limited permissions.

### ISSUE THREAD

**Issue by nitanmarcel** [KernelSU-Next/KernelSU-Next#102]
### Please check before submitting an issue

- [x] I have searched the issues and haven't found anything relevant
- [x] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I just moved to KenelSU-Next from KernelSU and I noticed that I can't access `/data/local/tmp` without using the adb template, and after using the adb template some binaries like frida can't access some information such as the selinux status.

### To Reproduce

- 1: Give su permissions to adb shell
- 2: Try to cd into /data/local/tmp
- 3: Run the ls command

### Expected behavior

In the normal KernelSU, the directory `/data/local/tmp` was unrestricted for root processes. Which is not the case in KenelSU-Next version

### Device info

[KernelSU_bugreport_2025-01-28_14_04.tar.gz](https://github.com/user-attachments/files/18573130/KernelSU_bugreport_2025-01-28_14_04.tar.gz)

- Device: CMF Phone 1
- OS Version: Android 15
- KernelSU Version: 12335
- Kernel Version: 6.1.78

**Comment by backslashxx** [comment]
https://github.com/tiann/KernelSU/commit/62ef18b5600287735e726b1ffdd2eec890e69cb1
https://github.com/tiann/KernelSU/pull/2387

**Comment by nitanmarcel** [comment]
> [tiann/KernelSU@62ef18b](https://github.com/tiann/KernelSU/commit/62ef18b5600287735e726b1ffdd2eec890e69cb1) [tiann/KernelSU#2387](https://github.com/tiann/KernelSU/pull/2387)

I can confirm that the bug is now gone with the latest commits

**Comment by backslashxx** [comment]
ye, its like you can open a lot of stuff on /data, noticed that too when trying to list /data/data

**Comment by rifsxd** [comment]
should be fixed with [kernel: clear securebits](https://github.com/rifsxd/KernelSU-Next/commit/87fc6b27844b06ef2da4fc362d6d8ff5fe1d4573) picked before ksu official, you can close the issue after testing the latest commit.

**Comment by MIkeeJY** [comment]
<img width="217" alt="Image" src="https://github.com/user-attachments/assets/f0b2ae39-9444-4f9b-9c2d-ec06298be695" />  Still not work

**Comment by MIkeeJY** [comment]
@rifsxd  data and data/data still can not use cmd "ls"  with the lastest CI version

<img width="224" alt="Image" src="https://github.com/user-attachments/assets/1277d637-8692-4d21-82b1-b525d94a6aa1" />

**Comment by rifsxd** [comment]
> [@rifsxd](https://github.com/rifsxd) data and data/data still can not use cmd "ls" with the lastest CI version
> 
> <img alt="Image" width="224" src="https://private-user-images.githubusercontent.com/8580762/409823385-1277d637-8692-4d21-82b1-b525d94a6aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3NzkyMjYsIm5iZiI6MTczODc3ODkyNiwicGF0aCI6Ii84NTgwNzYyLzQwOTgyMzM4NS0xMjc3ZDYzNy04NjkyLTRkMjEtODJiMS1iNTI1ZDk0YTZhYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMDVUMTgwODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk5MjFjZTNiYTMzNzlhNmYwZjU3MjYyNzEwZDBjNDliMTIwNDNlMWJkNWVjMjM2MDYzMTRkMDk3MmU3ZDE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QRHbjkYJtbGlfQL9rgnAhRIDOnJGhFu-D_gbVMugpTA">

Update to latest version for kernel driver

**Comment by MIkeeJY** [comment]
@rifsxd I can not see your picture, can u tell me the latest version version number for SUSFS?
